name: Build and Deploy Forecast

on:
    workflow_dispatch:
        inputs:
            zone:
                description: "Zone for the forecast. Run forecast -h for full list"
                type: choice
                options:
                    - Central Interior
                    - Culebra
                    - Eastern Interior
                    - Mayaguez and Vicinity
                    - North Central
                    - Northeast
                    - Northwest
                    - Ponce and Vicinity
                    - San Juan and Vicinity
                    - Southeast
                    - Southwest
                    - Vieques
                    - Western Interior
                default: "Mayaguez and Vicinity"
            limit:
                description: "Limit {1-7}"
                required: false
                default: "7"

jobs:
    build:
        runs-on: ubuntu-latest

        permissions:
            contents: read
            pages: write
            id-token: write

        env:
            ZONE: ${{ github.event.inputs.zone }}
            LIMIT: ${{ github.event.inputs.limit }}
            OUTPUT_DIR: ${{ github.workspace }}/output
            FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Python
              uses: actions/setup-python@v5
              with:
                  python-version: "3.12"

            - name: Install project
              run: |
                  python -m pip install --upgrade pip
                  pip install ./SunCastPy

            - name: Run bash script
              run: |
                  chmod +x ./scripts/github/create-forecast-report.sh
                  ./scripts/github/create-forecast-report.sh

            - name: Upload Pages artifact
              uses: actions/upload-pages-artifact@v3
              with:
                  path: ${{ env.OUTPUT_DIR }}

    deploy:
        needs: build
        runs-on: ubuntu-latest

        permissions:
            pages: write
            id-token: write

        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}

        steps:
            - name: Deploy
              uses: actions/deploy-pages@v4
              id: deployment
