name: Pull Request

on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write
  actions: read
  checks: write

defaults:
  run:
    working-directory: SunCastPy

env:
  REPORTS_DIR: ${{ github.workspace }}/SunCastPy/reports
  SCRIPTS_DIR: ${{ github.workspace }}/scripts

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      # Setup
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          bash ${SCRIPTS_DIR}/github/install-project.sh [tests]

      # Pytest
      - name: Run tests + generate reports
        id: pytest
        run: |
          mkdir -p $REPORTS_DIR
          pytest 
        continue-on-error: true

      - name: Publish test summary to PR
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Pytest Results
          path: ${{ env.REPORTS_DIR }}/junit.xml
          reporter: java-junit

      # Pytest Coverage
      - name: Run coverage check
        uses: karilys-dev/python-coverage-check-action@v11
        if: always()
        with:
          working-directory: SunCastPy

      # Post Actions
      - name: Upload test reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-reports
          path: ${{ env.REPORTS_DIR }}/
          retention-days: 3

      - name: Fail job if tests failed
        if: steps.pytest.outcome == 'failure'
        run: exit 1
