name: Pull Request

on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write
  actions: read
  checks: write

defaults:
  run:
    working-directory: SunCastPy

env:
  OUTPUT_DIR: ${{ github.workspace }}/SunCastPy/reports
  SCRIPTS_DIR: ${{ github.workspace }}/scripts

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      # Setup
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies and setup working environment
        run: |
          bash ${SCRIPTS_DIR}/github/install-project.sh [tests]
          mkdir -p $OUTPUT_DIR

      # Pytest
      - name: Run tests + generate reports
        id: pytest
        run: pytest
        continue-on-error: true

      - name: Publish test summary to PR
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Pytest Results
          path: ${{ env.OUTPUT_DIR }}/junit.xml
          reporter: java-junit

      # Pytest Coverage
      - name: Run coverage check
        uses: karilys-dev/python-coverage-check-action@v1
        if: always()
        with:
          working-directory: SunCastPy

      # Post Actions
      - name: Upload test reports
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: test-reports
          path: ${{ env.OUTPUT_DIR }}/
          retention-days: 3

      - name: Fail job if tests failed
        if: steps.pytest.outcome == 'failure'
        run: exit 1

  robot:
    runs-on: ubuntu-latest
    steps:
      # Setup
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Setup robot-framework
        run: ${{ env.SCRIPTS_DIR }}/ci-cd/run-robot.sh -i

      - name: Run robot framework
        id: robot-framework
        run: ${{ env.SCRIPTS_DIR }}/ci-cd/run-robot.sh -r
        continue-on-error: false

      - name: Publish Robot Test Results
        if: always()
        uses: mikepenz/action-junit-report@v5
        with:
          check_name: Robot-Framework Report
          report_paths: ${{ env.OUTPUT_DIR }}/robot/xunit.xml
          include_passed: true
          detailed_summary: true
          require_tests: true

      - name: Setup Semgrep
        run: ${{ env.SCRIPTS_DIR }}/ci-cd/run-semgrep.sh -i

      - name: Run Semgrep framework
        id: Semgrep
        run: ${{ env.SCRIPTS_DIR }}/ci-cd/run-semgrep.sh -r
        continue-on-error: false

      - name: Publish semgrep Test Results
        if: always()
        uses: mikepenz/action-junit-report@v5
        with:
          check_name: Semgrep Report
          report_paths: ${{ env.OUTPUT_DIR }}/semgrep/result.xml
          include_passed: true
          detailed_summary: true
          require_tests: true

      - name: Upload test reports
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: test-reports
          path: ${{ env.OUTPUT_DIR }}/
          retention-days: 3
